-- AlterTable
ALTER TABLE "Events" ALTER COLUMN "priseFrom" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "priseTo" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Quests" ALTER COLUMN "reffReward" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "rewardFrom" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "rewardTo" SET DATA TYPE DOUBLE PRECISION;
